server:
  port: 8082
spring:
  application:
    name: diary-service
  datasource:
    url: jdbc:postgresql://localhost:5432/diary
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  mvc:
    problemdetails:
      enabled: true
diary:
  kek-base64: "YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY="
management:
  endpoints:
    web:
      exposure:
        include: health
