package io.graphrag.generated.diary;

import io.graphrag.testlib.api.TestScope;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.notNullValue;

/**
 * Generated by test-generator. DO NOT EDIT.
 * endpoint: GET /internal/diaries/{id}/content (get-internal-diaries-id-content) — 3 scenario(s)
 */
class DiaryGetContentTest {

    private TestScope scope;

    @BeforeEach
    void setUp() {
        scope = TestScope.create();
    }

    @AfterEach
    void cleanup() {
        scope.cleanup();
    }

    @Test
    void s500_1() throws Exception {
        scope.rest().given()
            .contentType("application/json")
        .when()
            .get("/internal/diaries/probe-id-98829/content")
        .then()
            .statusCode(500)
            .body("timestamp", notNullValue())
            .body("status", notNullValue())
            .body("error", notNullValue())
            .body("path", notNullValue());
    }

    @Test
    void s404_1() throws Exception {
        scope.rest().given()
            .contentType("application/json")
        .when()
            .get("/internal/diaries/missing/content")
        .then()
            .statusCode(404)
            .body("type", notNullValue())
            .body("title", notNullValue())
            .body("status", notNullValue())
            .body("detail", notNullValue())
            .body("instance", notNullValue());
    }

    @Test
    void s404_2() throws Exception {
        scope.rest().given()
            .contentType("application/json")
        .when()
            .get("/internal/diaries//content")
        .then()
            .statusCode(404)
            .body("type", notNullValue())
            .body("title", notNullValue())
            .body("status", notNullValue())
            .body("detail", notNullValue())
            .body("instance", notNullValue());
    }
}
