package io.graphrag.generated.diary;

import io.graphrag.testlib.api.TestScope;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.notNullValue;

/**
 * Generated by test-generator. DO NOT EDIT.
 * endpoint: POST /internal/diaries (post-internal-diaries) — 2 scenario(s)
 */
class DiaryPostTest {

    private TestScope scope;

    @BeforeEach
    void setUp() {
        scope = TestScope.create();
    }

    @AfterEach
    void cleanup() {
        scope.cleanup();
    }

    @Test
    void s201_1() throws Exception {
        scope.kafka().subscribe("diary.created");
        scope.rest().given()
            .contentType("application/json")
            .body("{\"userId\":\"sample-userId\",\"title\":\"sample-title\",\"content\":\"sample-content\",\"primaryEmotion\":\"sample-primaryEmotion\",\"energyScore\":1}")
        .when()
            .post("/internal/diaries")
        .then()
            .statusCode(201)
            .body("diaryId", notNullValue())
            .body("userId", equalTo("sample-userId"))
            .body("primaryEmotion", equalTo("sample-primaryEmotion"))
            .body("energyScore", equalTo(1))
            .body("timestamp", notNullValue());
        {
            org.apache.kafka.clients.consumer.ConsumerRecord<String, String> record =
                scope.kafka().consumeNextRecord("diary.created", null, java.time.Duration.ofSeconds(5));
            org.junit.jupiter.api.Assertions.assertNotNull(record);
            org.skyscreamer.jsonassert.JSONAssert.assertEquals(
                "{\"eventId\":\"565a865c-c9df-4fa6-a9ef-2f02b435b477\",\"userId\":\"sample-userId\",\"primaryEmotion\":\"sample-primaryEmotion\",\"energyScore\":1,\"occurredAt\":\"2026-06-20T05:59:26.398574Z\"}", record.value(), false);
        }
    }

    @Test
    void s400_1() throws Exception {
        scope.rest().given()
            .contentType("application/json")
            .body("{\"userId\":\"sample-userId\",\"title\":\"sample-title\",\"content\":\"sample-content\",\"primaryEmotion\":\"sample-primaryEmotion\",\"energyScore\":0}")
        .when()
            .post("/internal/diaries")
        .then()
            .statusCode(400)
            .body("type", notNullValue())
            .body("title", notNullValue())
            .body("status", notNullValue())
            .body("detail", notNullValue())
            .body("instance", notNullValue());
    }
}
